### ISSUE TITLE
"No Babel config file detected"

### ISSUE THREAD

**Issue by rowild** [TYPO3-Headless/pwa-demo#43]
In order to play around with `nuxt-typo3` you provide an installation guide here, which I followed:
https://github.com/TYPO3-Initiatives/pwa-demo#nuxt-typo3-development-together-with-typo3-pwa-demo-api

The resulting folder structure looks like this:
![Bildschirmfoto 2021-10-25 um 12 00 37](https://user-images.githubusercontent.com/213803/138675745-68c1522b-fd1c-421e-b41a-ee4b2919ab49.png)

As you can see, there are console errors that say:
`Parsing error: No Babel config file detected for /.../typo3-headless-nuxt-pwa/nuxt-typo3/babel.config.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files.`

starting with the babel file itself. I wonder why I get these errors? It obviously means that you have something installed that I don't. If that is the case, this has to be figured out and mentioned in the documentation.

I kindly ask you to respond sooner this time, not only months later and only because there is a code sprint coming up in 2 days – thank you!

**Comment by lukaszuznanski** [comment]
Looks like some kind of misconfiguration. Closing for now, please reopen if you have any more informations, but I believe this belongs to nuxt-typo3, not pwa-demo.
