### ISSUE TITLE
Can't get the frontend running 

### ISSUE THREAD

**Issue by taunusweb** [TYPO3-Headless/pwa-demo#86]
Hi there,
just tried to get this running, Bac kend works well, but I can't get the frontend running:
```
Error: unknown command "setup-pwa-front" for "ddev"
Run 'ddev --help' for usage.
Task failed: Exec command 'ddev setup-pwa-front first-time' on the host (Taunusweb-22): exit status 255
A task failure does not mean that ddev failed, but your hook configuration has a command that failed.
command 'container-front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/taunusweb/pwa-demo/.ddev/commands/web/container-front
command 'front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/taunusweb/pwa-demo/.ddev/commands/web/front
Error: unknown command "pwa-front" for "ddev"
Run 'ddev --help' for usage.
Task failed: Exec command 'ddev pwa-front rebuild' on the host (Taunusweb-22): exit status 255
A task failure does not mean that ddev failed, but your hook configuration has a command that failed.
command 'container-front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/taunusweb/pwa-demo/.ddev/commands/web/container-front
command 'front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/taunusweb/pwa-demo/.ddev/commands/web/front
Error: unknown command "setup-pwa-front" for "ddev"
Run 'ddev --help' for usage.
Task failed: Exec command 'ddev setup-pwa-front post-start-info' on the host (Taunusweb-22): exit status 255
A task failure does not mean that ddev failed, but your hook configuration has a command that failed.
```
Do you have any hints?

**Comment by vaxul** [comment]
Same here. Following the [installation guide](https://github.com/TYPO3-Headless/pwa-demo#installation) doesn't work.

My DDEV within WSL:
```
 ITEM             VALUE
 DDEV version     v1.21.6
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.5
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.5
 docker           23.0.5
 docker-compose   v2.15.1
 docker-platform  docker-desktop
 mutagen          0.16.0
 os               linux
 router           drud/ddev-router:v1.21.5
 web              drud/ddev-webserver:v1.21.5
```

`ddev start` output:
> 
> command 'container-front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/username/projects/wsl.typo3-pwa-demo/.ddev/commands/web/container-front
> command 'front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/username/projects/wsl.typo3-pwa-demo/.ddev/commands/web/front
> 
> 
> Upgraded DDEV v1.22.3 is available!
> Please visit https://github.com/ddev/ddev/releases/tag/v1.22.3 to get the upgrade.
> For upgrade help see https://ddev.readthedocs.io/en/stable/users/install/
> 
> 
> Starting pwa-demo...
> Container ddev-ssh-agent  Recreate
> Container ddev-ssh-agent  Recreated
> Container ddev-ssh-agent  Started
> ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
> Using custom nginx configuration in /home/username/projects/wsl.typo3-pwa-demo/.ddev/nginx_full/nginx-site.conf
> Custom configuration is updated on restart.
> If you don't see your custom configuration taking effect, run 'ddev restart'.
> v1.21.5: Pulling from drud/ddev-dbserver-mariadb-10.3
> df6635ed1257: Already exists
> d5dcb717eef2: Already exists
> a070ce9ccedb: Already exists
> a053d9150480: Already exists
> 381d7acd8833: Pull complete
> 589a0f4fa64a: Pull complete
> c639e63296d1: Pull complete
> 705d9b9360b6: Pull complete
> c63a93d49143: Pull complete
> 4f4fb700ef54: Pull complete
> cb01a731160c: Pull complete
> 982135dba986: Pull complete
> d12ab63f7fab: Pull complete
> 112c23699509: Pull complete
> 9e61d5ae7fe0: Pull complete
> c9ccf874d5df: Pull complete
> 3c5741040871: Pull complete
> 9c2b6ba18e67: Pull complete
> a68f86072f55: Pull complete
> 54ecf2d9ca99: Pull complete
> a7a24dc1243f: Pull complete
> 996dc3c66023: Pull complete
> f378d51a0adc: Pull complete
> 314b3338b8ba: Pull complete
> Digest: sha256:3a45b2d0f1d4797aada9c23183c16c5fc6c4635146ad197722b7333cf0e23fad
> Status: Downloaded newer image for drud/ddev-dbserver-mariadb-10.3:v1.21.5
> docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.5
> Network ddev-pwa-demo_default  Created
> Container ddev-pwa-demo-web  Started
> Container ddev-pwa-demo-dba  Started
> Container ddev-pwa-demo-db  Started
> Container ddev-router  Started
> bash: /var/www/html/.ddev/import-if-empty.sh: /bin/bash^M: bad interpreter: No such file or directory
> Task failed: Exec command '/var/www/html/.ddev/import-if-empty.sh' in container/service 'web': exit status 126
> A task failure does not mean that ddev failed, but your hook configuration has a command that failed.
> Installing dependencies from lock file (including require-dev)
> Verifying lock file contents can be installed on current platform.
> Package operations: 122 installs, 0 updates, 0 removals
>   - Downloading firebase/php-jwt (v6.5.0)
>   - Downloading typo3fluid/fluid (2.8.0)
>   - Downloading masterminds/html5 (2.8.0)
>   - Downloading symfony/yaml (v6.3.0)
>   - Downloading symfony/uid (v6.3.0)
>   - Downloading symfony/routing (v6.3.0)
>   - Downloading symfony/deprecation-contracts (v3.3.0)
>   - Downloading symfony/options-resolver (v6.3.0)
>   - Downloading symfony/rate-limiter (v6.3.0)
>   - Downloading symfony/mime (v6.3.0)
>   - Downloading psr/clock (1.0.0)
>   - Downloading symfony/clock (v6.3.0)
>   - Downloading symfony/messenger (v6.3.0)
>   - Downloading symfony/service-contracts (v3.3.0)
>   - Downloading symfony/event-dispatcher-contracts (v3.3.0)
>   - Downloading symfony/event-dispatcher (v6.3.0)
>   - Downloading symfony/mailer (v6.3.0)
>   - Downloading symfony/polyfill-php83 (v1.27.0)
>   - Downloading symfony/http-foundation (v6.3.0)
>   - Downloading symfony/finder (v6.3.0)
>   - Downloading symfony/filesystem (v6.3.0)
>   - Downloading symfony/var-exporter (v6.3.0)
>   - Downloading symfony/cache-contracts (v3.3.0)
>   - Downloading symfony/cache (v6.3.0)
>   - Downloading symfony/expression-language (v6.3.0)
>   - Downloading doctrine/deprecations (v1.1.0)
>   - Downloading symfony/doctrine-messenger (v6.3.0)
>   - Downloading symfony/dependency-injection (v6.3.0)
>   - Downloading symfony/string (v6.3.0)
>   - Downloading symfony/console (v6.3.0)
>   - Downloading symfony/config (v6.3.0)
>   - Downloading guzzlehttp/promises (1.5.3)
>   - Downloading typo3/cms-core (v12.4.1)
>   - Downloading symfony/property-info (v6.3.0)
>   - Downloading symfony/property-access (v6.3.0)
>   - Downloading phpstan/phpdoc-parser (1.22.0)
>   - Downloading phpdocumentor/type-resolver (1.7.2)
>   - Downloading typo3/cms-extbase (v12.4.1)
>   - Downloading typo3/cms-fluid (v12.4.1)
>   - Downloading nikic/php-parser (v4.15.5)
>   - Downloading typo3/cms-install (v12.4.1)
>   - Downloading friendsoftypo3/headless (v4.0.0)
>   - Downloading typo3/cms-frontend (v12.4.1)
>   - Downloading typo3/cms-extensionmanager (v12.4.1)
>   - Downloading typo3/cms-backend (v12.4.1)
>   - Downloading symfony/process (v6.3.0)
>   - Downloading helhum/php-error-reporting (v1.0.1)
>   - Downloading helhum/config-loader (v0.12.5)
>   - Downloading helhum/typo3-console (dev-main b1e230a)
>   - Downloading typo3/cms-fluid-styled-content (v12.4.1)
>   - Downloading friendsoftypo3/fontawesome-provider (v1.0.3)
>   - Downloading mask/mask (v8.1.5)
>   - Downloading symfony/var-dumper (v6.3.0)
>   - Downloading typo3/cms-adminpanel (v12.4.1)
>   - Downloading typo3/cms-belog (v12.4.1)
>   - Downloading typo3/cms-beuser (v12.4.1)
>   - Downloading typo3/cms-dashboard (v12.4.1)
>   - Downloading typo3/cms-felogin (v12.4.1)
>   - Downloading typo3/cms-filemetadata (v12.4.1)
>   - Downloading typo3/cms-form (v12.4.1)
>   - Downloading typo3/cms-impexp (v12.4.1)
>   - Downloading typo3/cms-indexed-search (v12.4.1)
>   - Downloading typo3/cms-info (v12.4.1)
>   - Downloading typo3/cms-linkvalidator (v12.4.1)
>   - Downloading typo3/cms-lowlevel (v12.4.1)
>   - Downloading typo3/cms-opendocs (v12.4.1)
>   - Downloading typo3/cms-reactions (v12.4.1)
>   - Downloading typo3/cms-recycler (v12.4.1)
>   - Downloading typo3/cms-redirects (v12.4.1)
>   - Downloading typo3/cms-reports (v12.4.1)
>   - Downloading typo3/cms-rte-ckeditor (v12.4.1)
>   - Downloading typo3/cms-scheduler (v12.4.1)
>   - Downloading typo3/cms-seo (v12.4.1)
>   - Downloading typo3/cms-setup (v12.4.1)
>   - Downloading typo3/cms-sys-note (v12.4.1)
>   - Downloading typo3/cms-t3editor (v12.4.1)
>   - Downloading typo3/cms-tstemplate (v12.4.1)
>   - Downloading typo3/cms-viewpage (v12.4.1)
>   - Downloading typo3/cms-workspaces (v12.4.1)
>   - Downloading typo3/cms-filelist (v12.4.1)
>   - Installing typo3/cms-composer-installers (v5.0.0): Extracting archive
>   - Installing typo3/class-alias-loader (v1.1.4): Extracting archive
>   - Installing dasprid/enum (1.0.4): Extracting archive
>   - Installing bacon/bacon-qr-code (2.0.8): Extracting archive
>   - Installing christian-riesen/base32 (1.6.0): Extracting archive
>   - Installing psr/cache (3.0.0): Extracting archive
>   - Installing doctrine/lexer (3.0.0): Extracting archive
>   - Installing doctrine/annotations (2.0.1): Extracting archive
>   - Installing doctrine/cache (2.2.0): Extracting archive
>   - Installing doctrine/event-manager (2.0.0): Extracting archive
>   - Installing doctrine/instantiator (2.0.0): Extracting archive
>   - Installing enshrined/svg-sanitize (0.15.4): Extracting archive
>   - Installing firebase/php-jwt (v6.5.0): Extracting archive
>   - Installing symfony/polyfill-mbstring (v1.27.0): Extracting archive
>   - Installing typo3fluid/fluid (2.8.0): Extracting archive
>   - Installing psr/log (3.0.0): Extracting archive
>   - Installing masterminds/html5 (2.8.0): Extracting archive
>   - Installing typo3/html-sanitizer (v2.1.1): Extracting archive
>   - Installing typo3/cms-cli (3.1.0): Extracting archive
>   - Installing symfony/polyfill-ctype (v1.27.0): Extracting archive
>   - Installing symfony/yaml (v6.3.0): Extracting archive
>   - Installing symfony/polyfill-uuid (v1.27.0): Extracting archive
>   - Installing symfony/uid (v6.3.0): Extracting archive
>   - Installing symfony/routing (v6.3.0): Extracting archive
>   - Installing symfony/deprecation-contracts (v3.3.0): Extracting archive
>   - Installing symfony/options-resolver (v6.3.0): Extracting archive
>   - Installing symfony/rate-limiter (v6.3.0): Extracting archive
>   - Installing symfony/polyfill-php72 (v1.27.0): Extracting archive
>   - Installing symfony/polyfill-intl-normalizer (v1.27.0): Extracting archive
>   - Installing symfony/polyfill-intl-idn (v1.27.0): Extracting archive
>   - Installing symfony/mime (v6.3.0): Extracting archive
>   - Installing psr/clock (1.0.0): Extracting archive
>   - Installing symfony/clock (v6.3.0): Extracting archive
>   - Installing symfony/messenger (v6.3.0): Extracting archive
>   - Installing psr/container (2.0.2): Extracting archive
>   - Installing symfony/service-contracts (v3.3.0): Extracting archive
>   - Installing psr/event-dispatcher (1.0.0): Extracting archive
>   - Installing symfony/event-dispatcher-contracts (v3.3.0): Extracting archive
>   - Installing symfony/event-dispatcher (v6.3.0): Extracting archive
>   - Installing egulias/email-validator (4.0.1): Extracting archive
>   - Installing symfony/mailer (v6.3.0): Extracting archive
>   - Installing symfony/polyfill-php80 (v1.27.0): Extracting archive
>   - Installing symfony/polyfill-php83 (v1.27.0): Extracting archive
>   - Installing symfony/http-foundation (v6.3.0): Extracting archive
>   - Installing symfony/finder (v6.3.0): Extracting archive
>   - Installing symfony/filesystem (v6.3.0): Extracting archive
>   - Installing symfony/var-exporter (v6.3.0): Extracting archive
>   - Installing symfony/cache-contracts (v3.3.0): Extracting archive
>   - Installing symfony/cache (v6.3.0): Extracting archive
>   - Installing symfony/expression-language (v6.3.0): Extracting archive
>   - Installing doctrine/deprecations (v1.1.0): Extracting archive
>   - Installing doctrine/dbal (3.6.2): Extracting archive
>   - Installing symfony/doctrine-messenger (v6.3.0): Extracting archive
>   - Installing symfony/dependency-injection (v6.3.0): Extracting archive
>   - Installing symfony/polyfill-intl-grapheme (v1.27.0): Extracting archive
>   - Installing symfony/string (v6.3.0): Extracting archive
>   - Installing symfony/console (v6.3.0): Extracting archive
>   - Installing symfony/config (v6.3.0): Extracting archive
>   - Installing scssphp/scssphp (v1.11.0): Extracting archive
>   - Installing psr/http-message (2.0): Extracting archive
>   - Installing psr/http-server-handler (1.0.2): Extracting archive
>   - Installing psr/http-server-middleware (1.0.2): Extracting archive
>   - Installing psr/http-factory (1.0.2): Extracting archive
>   - Installing psr/http-client (1.0.2): Extracting archive
>   - Installing lolli42/finediff (1.0.2): Extracting archive
>   - Installing ralouphie/getallheaders (3.0.3): Extracting archive
>   - Installing guzzlehttp/psr7 (2.5.0): Extracting archive
>   - Installing guzzlehttp/promises (1.5.3): Extracting archive
>   - Installing guzzlehttp/guzzle (7.7.0): Extracting archive
>   - Installing typo3/cms-core (v12.4.1): Extracting archive
>   - Installing symfony/property-info (v6.3.0): Extracting archive
>   - Installing symfony/property-access (v6.3.0): Extracting archive
>   - Installing phpstan/phpdoc-parser (1.22.0): Extracting archive
>   - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
>   - Installing phpdocumentor/type-resolver (1.7.2): Extracting archive
>   - Installing webmozart/assert (1.11.0): Extracting archive
>   - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
>   - Installing typo3/cms-extbase (v12.4.1): Extracting archive
>   - Installing typo3/cms-fluid (v12.4.1): Extracting archive
>   - Installing nikic/php-parser (v4.15.5): Extracting archive
>   - Installing typo3/cms-install (v12.4.1): Extracting archive
>   - Installing friendsoftypo3/headless (v4.0.0): Extracting archive
>   - Installing typo3/cms-frontend (v12.4.1): Extracting archive
>   - Installing typo3/cms-extensionmanager (v12.4.1): Extracting archive
>   - Installing typo3/cms-backend (v12.4.1): Extracting archive
>   - Installing symfony/process (v6.3.0): Extracting archive
>   - Installing helhum/php-error-reporting (v1.0.1): Extracting archive
>   - Installing helhum/config-loader (v0.12.5): Extracting archive
>   - Installing helhum/typo3-console (dev-main b1e230a): Extracting archive
>   - Installing typo3/cms-fluid-styled-content (v12.4.1): Extracting archive
>   - Installing friendsoftypo3/fontawesome-provider (v1.0.3): Extracting archive
>   - Installing mask/mask (v8.1.5): Extracting archive
>   - Installing pwademo/site-package (1.0.0): Symlinking from packages/site_package
>   - Installing symfony/var-dumper (v6.3.0): Extracting archive
>   - Installing typo3/cms-adminpanel (v12.4.1): Extracting archive
>   - Installing typo3/cms-belog (v12.4.1): Extracting archive
>   - Installing typo3/cms-beuser (v12.4.1): Extracting archive
>   - Installing typo3/cms-dashboard (v12.4.1): Extracting archive
>   - Installing typo3/cms-felogin (v12.4.1): Extracting archive
>   - Installing typo3/cms-filemetadata (v12.4.1): Extracting archive
>   - Installing typo3/cms-form (v12.4.1): Extracting archive
>   - Installing typo3/cms-impexp (v12.4.1): Extracting archive
>   - Installing typo3/cms-indexed-search (v12.4.1): Extracting archive
>   - Installing typo3/cms-info (v12.4.1): Extracting archive
>   - Installing typo3/cms-linkvalidator (v12.4.1): Extracting archive
>   - Installing typo3/cms-lowlevel (v12.4.1): Extracting archive
>   - Installing typo3/cms-opendocs (v12.4.1): Extracting archive
>   - Installing typo3/cms-reactions (v12.4.1): Extracting archive
>   - Installing typo3/cms-recycler (v12.4.1): Extracting archive
>   - Installing typo3/cms-redirects (v12.4.1): Extracting archive
>   - Installing typo3/cms-reports (v12.4.1): Extracting archive
>   - Installing typo3/cms-rte-ckeditor (v12.4.1): Extracting archive
>   - Installing typo3/cms-scheduler (v12.4.1): Extracting archive
>   - Installing typo3/cms-seo (v12.4.1): Extracting archive
>   - Installing typo3/cms-setup (v12.4.1): Extracting archive
>   - Installing typo3/cms-sys-note (v12.4.1): Extracting archive
>   - Installing typo3/cms-t3editor (v12.4.1): Extracting archive
>   - Installing typo3/cms-tstemplate (v12.4.1): Extracting archive
>   - Installing typo3/cms-viewpage (v12.4.1): Extracting archive
>   - Installing typo3/cms-workspaces (v12.4.1): Extracting archive
>   - Installing typo3/cms-filelist (v12.4.1): Extracting archive
>   - Installing typo3/minimal (v12.4.0)
> Generating autoload files
> Generating class alias map file
> 50 packages you are using are looking for funding.
> Use the `composer fund` command to find out more!
> command 'container-front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/username/projects/wsl.typo3-pwa-demo/.ddev/commands/web/container-front
> command 'front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/username/projects/wsl.typo3-pwa-demo/.ddev/commands/web/front
> Error: unknown command "setup-pwa-front" for "ddev"
> Run 'ddev --help' for usage.
> Task failed: Exec command 'ddev setup-pwa-front first-time' on the host (username-xps): exit status 255
> A task failure does not mean that ddev failed, but your hook configuration has a command that failed.
> command 'container-front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/username/projects/wsl.typo3-pwa-demo/.ddev/commands/web/container-front
> command 'front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/username/projects/wsl.typo3-pwa-demo/.ddev/commands/web/front
> Error: unknown command "pwa-front" for "ddev"
> Run 'ddev --help' for usage.
> Task failed: Exec command 'ddev pwa-front rebuild' on the host (username-xps): exit status 255
> A task failure does not mean that ddev failed, but your hook configuration has a command that failed.
> command 'container-front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/username/projects/wsl.typo3-pwa-demo/.ddev/commands/web/container-front
> command 'front' contains CRLF, please convert to Linux-style linefeeds with dos2unix or another tool, skipping /home/username/projects/wsl.typo3-pwa-demo/.ddev/commands/web/front
> Error: unknown command "setup-pwa-front" for "ddev"
> Run 'ddev --help' for usage.
> Task failed: Exec command 'ddev setup-pwa-front post-start-info' on the host (username-xps): exit status 255
> A task failure does not mean that ddev failed, but your hook configuration has a command that failed.
> Successfully started pwa-demo
> Project can be reached at https://pwa-demo.ddev.site https://api.pwa-demo.ddev.site https://127.0.0.1:61228

**Comment by tmotyl** [comment]
I've just checked and file container-front does NOT contain windows line endings.
Are you using the most recent version from master branch - this version I've tested?

Most probably your git configuration is converting the endings automatically from linux to windows when checking out.

You can adjust this in your git configuration. see:
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

additionally I will try to add config for these files to .gitattributes, so it doesn't depend on local machines config.

**Comment by tmotyl** [comment]
here is the patch (which will work for new checkouts) https://github.com/TYPO3-Headless/pwa-demo/commit/414edb235d43fcc2acd9ff591e480f73032ad4ea

**Comment by vaxul** [comment]
Thanks for the fix, this worked. But now I'm stuck on 

> 3. Access frontend in your browser: https://pwa-demo.ddev.site/
> 4. Access TYPO3 backend: https://api.pwa-demo.ddev.site/typo3

I've got the error on https://api.pwa-demo.ddev.site/typo3:

> #1146 Doctrine\DBAL\Exception\TableNotFoundException
> An exception occurred while executing a query: Table 'db.sys_news' doesn't exist

It seems, that the database is not initialized/imported correctly.

**Comment by vaxul** [comment]
Yes this worked. :) Should this in the install guide?

**Comment by tmotyl** [comment]
it should be triggered automatically on first run, see: https://github.com/TYPO3-Headless/pwa-demo/blob/master/.ddev/config.yaml#L19

Then its documented at the end of the readme.

Do you think this should be made more clear? 
Could you send the PR with improvement?

**Comment by vaxul** [comment]
Yes, if I follow the installation guide, and it won't work, it might be a good idea to link some kind of troubleshooting.
